site_name: Two-Fast-Auth
site_description: 2FA middleware for FastAPI applications
site_url: https://rennf93.github.io/two-fast-auth/latest/
repo_name: rennf93/two-fast-auth
repo_url: https://github.com/rennf93/two-fast-auth
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark-green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dark-green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.svg
  favicon: assets/favicon.svg

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial:
    - First Steps: tutorial/first-steps.md
    - Core Module Guide: tutorial/two-factor-auth.md
    - Middleware Guide: tutorial/two-factor-middleware.md
    - Example Implementation: tutorial/example_implementation.md
    - Encryption Example Implementation: tutorial/example_implementation_encryption.md
    - Example Application: tutorial/example_app.md
    - Encryption Example Application: tutorial/example_app_encryption.md
  - API Reference:
    - Core Module: core/core.md
    - Middleware: middleware/middleware.md
    - Encryption: crypto/encryption.md
  - Release Notes: release-notes.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - def_list

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [two_fast_auth]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
            docstring_style: google
            show_if_no_docstring: true
            filters: ["!^_"]
            merge_init_into_class: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rennf93/two-fast-auth
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/two-fast-auth/

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by using our
            <a href="https://github.com/rennf93/two-fast-auth/issues/new">issue tracker</a>.

  generator: false
  meta:
    - property: og:type
      content: website
    - property: og:title
      content: Two-Fast-Auth - Two-Factor Authentication Middleware for FastAPI
    - property: og:description
      content: 2FA middleware for FastAPI applications
    - property: og:image
      content: https://rennf93.github.io/two-fast-auth/assets/big_logo.svg
    - name: keywords
      content: fastapi, security, middleware, python, 2fa, two-factor authentication

  version:
    provider: mike
    default: latest
    version_selector: true
    json_file: /two-fast-auth/versions.json

  author:
    name: Renzo Franceschini
    url: https://github.com/rennf93

copyright: Two-Fast-Auth by

extra_css:
  - css/custom.css